name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Clone repo
        run: git clone https://github.com/LUniversiteNumerique/parcours-hybridation
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go run ./main.go
